-- ============================================
-- SNOWPULSE - Dynamic Tables
-- Auto-refresh when upstream RAW data changes
-- No Tasks needed — Snowflake handles it!
-- ============================================

USE ROLE SNOWPULSE_ROLE;
USE DATABASE SNOWPULSE_DB;
USE WAREHOUSE SNOWPULSE_WH;

-- ============================================
-- 1. DAILY OHLCV (flattened from RAW_TRADES)
-- ============================================
CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.DAILY_OHLCV
    TARGET_LAG = '1 minute'
    WAREHOUSE = SNOWPULSE_WH
    COMMENT = 'Daily OHLCV bars - flattened from RAW_TRADES via Snowpipe Streaming (deduplicated)'
AS
SELECT
    RECORD_CONTENT:ticker::STRING           AS TICKER,
    TO_DATE(TO_TIMESTAMP_NTZ(
        RECORD_CONTENT:t::NUMBER / 1000
    ))                                      AS TRADE_DATE,
    RECORD_CONTENT:o::FLOAT                 AS OPEN_PRICE,
    RECORD_CONTENT:h::FLOAT                 AS HIGH_PRICE,
    RECORD_CONTENT:l::FLOAT                 AS LOW_PRICE,
    RECORD_CONTENT:c::FLOAT                 AS CLOSE_PRICE,
    RECORD_CONTENT:v::FLOAT                 AS VOLUME,
    RECORD_CONTENT:vw::FLOAT                AS VWAP,
    RECORD_CONTENT:n::NUMBER                AS NUM_TRANSACTIONS,
    RECORD_METADATA:ingested_at::TIMESTAMP_NTZ AS INGESTED_AT
FROM RAW.RAW_TRADES
QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKER, TRADE_DATE ORDER BY INGESTED_AT DESC) = 1;

-- ============================================
-- 2. DAILY RETURNS (% change day over day)
-- ============================================
CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.DAILY_RETURNS
    TARGET_LAG = '1 minute'
    WAREHOUSE = SNOWPULSE_WH
    COMMENT = 'Daily returns calculated from DAILY_OHLCV - auto-refreshes when upstream changes'
AS
SELECT
    TICKER,
    TRADE_DATE,
    CLOSE_PRICE,
    LAG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE) AS PREV_CLOSE,
    ROUND(
        (CLOSE_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE))
        / NULLIF(LAG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE), 0)
        * 100, 2
    ) AS DAILY_RETURN_PCT,
    VOLUME,
    VWAP
FROM ANALYTICS.DAILY_OHLCV;

-- ============================================
-- 3. MOVING AVERAGES (SMA 5, 10, 20 days)
-- ============================================
CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.MOVING_AVERAGES
    TARGET_LAG = '1 minute'
    WAREHOUSE = SNOWPULSE_WH
    COMMENT = 'Simple Moving Averages (5/10/20 days) - key technical indicator'
AS
SELECT
    TICKER,
    TRADE_DATE,
    CLOSE_PRICE,
    ROUND(AVG(CLOSE_PRICE) OVER (
        PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 4 PRECEDING AND CURRENT ROW
    ), 2) AS SMA_5,
    ROUND(AVG(CLOSE_PRICE) OVER (
        PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 9 PRECEDING AND CURRENT ROW
    ), 2) AS SMA_10,
    ROUND(AVG(CLOSE_PRICE) OVER (
        PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW
    ), 2) AS SMA_20,
    -- Signal: SMA5 crosses above SMA20 = bullish
    CASE
        WHEN AVG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 4 PRECEDING AND CURRENT ROW)
           > AVG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW)
        THEN 'BULLISH'
        ELSE 'BEARISH'
    END AS TREND_SIGNAL
FROM ANALYTICS.DAILY_OHLCV;

-- ============================================
-- 4. TICKER SUMMARY (latest stats per ticker)
-- Gold layer — ready for Streamlit dashboard
-- ============================================
CREATE OR REPLACE DYNAMIC TABLE GOLD.TICKER_SUMMARY
    TARGET_LAG = '1 minute'
    WAREHOUSE = SNOWPULSE_WH
    COMMENT = 'Latest summary per ticker - dashboard ready'
AS
WITH latest AS (
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY TICKER ORDER BY TRADE_DATE DESC) AS rn
    FROM ANALYTICS.DAILY_OHLCV
),
returns AS (
    SELECT TICKER, DAILY_RETURN_PCT,
        ROW_NUMBER() OVER (PARTITION BY TICKER ORDER BY TRADE_DATE DESC) AS rn
    FROM ANALYTICS.DAILY_RETURNS
    WHERE DAILY_RETURN_PCT IS NOT NULL
),
ma AS (
    SELECT TICKER, SMA_5, SMA_20, TREND_SIGNAL,
        ROW_NUMBER() OVER (PARTITION BY TICKER ORDER BY TRADE_DATE DESC) AS rn
    FROM ANALYTICS.MOVING_AVERAGES
)
SELECT
    l.TICKER,
    l.TRADE_DATE           AS LAST_TRADE_DATE,
    l.OPEN_PRICE,
    l.HIGH_PRICE,
    l.LOW_PRICE,
    l.CLOSE_PRICE          AS LAST_CLOSE,
    l.VOLUME               AS LAST_VOLUME,
    l.VWAP                 AS LAST_VWAP,
    r.DAILY_RETURN_PCT     AS LAST_RETURN_PCT,
    m.SMA_5,
    m.SMA_20,
    m.TREND_SIGNAL
FROM latest l
LEFT JOIN returns r ON l.TICKER = r.TICKER AND r.rn = 1
LEFT JOIN ma m ON l.TICKER = m.TICKER AND m.rn = 1
WHERE l.rn = 1;

-- ============================================
-- 5. RSI 14-Day (Relative Strength Index)
-- Classic momentum oscillator: LAG + AVG window
-- ============================================
CREATE OR REPLACE DYNAMIC TABLE ANALYTICS.RSI_14
    TARGET_LAG = '1 minute'
    WAREHOUSE = SNOWPULSE_WH
    COMMENT = 'RSI 14-day momentum indicator using LAG() and AVG() window functions'
AS
WITH daily_changes AS (
    SELECT
        TICKER,
        TRADE_DATE,
        CLOSE_PRICE,
        CLOSE_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE) AS PRICE_CHANGE
    FROM ANALYTICS.DAILY_OHLCV
),
gains_losses AS (
    SELECT
        TICKER,
        TRADE_DATE,
        CLOSE_PRICE,
        GREATEST(PRICE_CHANGE, 0) AS GAIN,
        ABS(LEAST(PRICE_CHANGE, 0)) AS LOSS
    FROM daily_changes
    WHERE PRICE_CHANGE IS NOT NULL
)
SELECT
    TICKER,
    TRADE_DATE,
    CLOSE_PRICE,
    ROUND(AVG(GAIN) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW), 4) AS AVG_GAIN_14,
    ROUND(AVG(LOSS) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW), 4) AS AVG_LOSS_14,
    ROUND(
        100 - (100 / (1 + NULLIF(
            AVG(GAIN) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW)
            / NULLIF(AVG(LOSS) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW), 0)
        , 0))), 2
    ) AS RSI_14,
    CASE
        WHEN 100 - (100 / (1 + NULLIF(
            AVG(GAIN) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW)
            / NULLIF(AVG(LOSS) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW), 0)
        , 0))) > 70 THEN 'OVERBOUGHT'
        WHEN 100 - (100 / (1 + NULLIF(
            AVG(GAIN) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW)
            / NULLIF(AVG(LOSS) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW), 0)
        , 0))) < 30 THEN 'OVERSOLD'
        ELSE 'NEUTRAL'
    END AS RSI_SIGNAL
FROM gains_losses;

-- ============================================
-- 6. BETA vs S&P 500 (manual regression)
-- Rolling 60-day beta: Cov(stock, SPY) / Var(SPY)
-- Uses SUM/COUNT window functions (REGR_SLOPE unsupported in sliding windows)
-- ============================================
CREATE OR REPLACE DYNAMIC TABLE GOLD.TICKER_BETA
    TARGET_LAG = '1 day'
    WAREHOUSE = SNOWPULSE_WH
    COMMENT = 'Rolling 60-day Beta vs S&P 500 (SPY) — manual Cov/Var regression'
AS
WITH stock_returns AS (
    SELECT
        TICKER,
        TRADE_DATE,
        (CLOSE_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE))
            / NULLIF(LAG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE), 0)
        AS DAILY_RETURN
    FROM ANALYTICS.DAILY_OHLCV
),
spy_returns AS (
    SELECT
        TRADE_DATE,
        (VALUE - LAG(VALUE) OVER (ORDER BY TRADE_DATE))
            / NULLIF(LAG(VALUE) OVER (ORDER BY TRADE_DATE), 0)
        AS DAILY_RETURN
    FROM ANALYTICS.MARKETPLACE_STOCK_PRICES
    WHERE TICKER = 'SPY'
      AND VARIABLE_NAME = 'Post-Market Close'
),
joined AS (
    SELECT
        s.TICKER,
        s.TRADE_DATE,
        s.DAILY_RETURN AS STOCK_RETURN,
        spy.DAILY_RETURN AS SPY_RETURN
    FROM stock_returns s
    INNER JOIN spy_returns spy ON s.TRADE_DATE = spy.TRADE_DATE
    WHERE s.TICKER != 'SPY'
      AND s.DAILY_RETURN IS NOT NULL
      AND spy.DAILY_RETURN IS NOT NULL
),
-- Rolling 60-day regression components
windowed AS (
    SELECT
        TICKER,
        TRADE_DATE,
        COUNT(*)                          OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS N,
        SUM(STOCK_RETURN * SPY_RETURN)    OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS SUM_XY,
        SUM(STOCK_RETURN)                 OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS SUM_Y,
        SUM(SPY_RETURN)                   OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS SUM_X,
        SUM(SPY_RETURN * SPY_RETURN)      OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS SUM_X2,
        SUM(STOCK_RETURN * STOCK_RETURN)  OVER (PARTITION BY TICKER ORDER BY TRADE_DATE ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS SUM_Y2
    FROM joined
)
SELECT
    TICKER,
    TRADE_DATE,
    -- Beta = (N*SUM(xy) - SUM(x)*SUM(y)) / (N*SUM(x²) - SUM(x)²)
    ROUND(
        (N * SUM_XY - SUM_X * SUM_Y)
        / NULLIF(N * SUM_X2 - POWER(SUM_X, 2), 0)
    , 4) AS BETA_60D,
    -- R² = correlation² = numerator² / (denom_x * denom_y)
    ROUND(
        POWER(N * SUM_XY - SUM_X * SUM_Y, 2)
        / NULLIF((N * SUM_X2 - POWER(SUM_X, 2)) * (N * SUM_Y2 - POWER(SUM_Y, 2)), 0)
    , 4) AS R_SQUARED_60D,
    CASE
        WHEN (N * SUM_XY - SUM_X * SUM_Y) / NULLIF(N * SUM_X2 - POWER(SUM_X, 2), 0) > 1.2 THEN 'HIGH_RISK'
        WHEN (N * SUM_XY - SUM_X * SUM_Y) / NULLIF(N * SUM_X2 - POWER(SUM_X, 2), 0) < 0.8 THEN 'DEFENSIVE'
        ELSE 'NEUTRAL'
    END AS RISK_PROFILE
FROM windowed
WHERE N >= 30;

-- ============================================
-- 7. SENTIMENT MOMENTUM — 7-day moving average
-- Detects if hype precedes price movements
-- ============================================
CREATE OR REPLACE DYNAMIC TABLE GOLD.SENTIMENT_MOMENTUM
    TARGET_LAG = '5 minutes'
    WAREHOUSE = SNOWPULSE_WH
    COMMENT = '7-day sentiment moving average to detect hype preceding price moves'
AS
WITH daily_sentiment AS (
    SELECT
        TICKER,
        PUBLISHED_AT::DATE AS SENTIMENT_DATE,
        ROUND(AVG(SENTIMENT_SCORE), 4) AS AVG_DAILY_SENTIMENT,
        COUNT(*) AS ARTICLE_COUNT
    FROM ANALYTICS.NEWS_SENTIMENT
    GROUP BY TICKER, PUBLISHED_AT::DATE
)
SELECT
    TICKER,
    SENTIMENT_DATE,
    AVG_DAILY_SENTIMENT,
    ARTICLE_COUNT,
    ROUND(AVG(AVG_DAILY_SENTIMENT) OVER (
        PARTITION BY TICKER ORDER BY SENTIMENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ), 4) AS SENTIMENT_MA_7D,
    ROUND(AVG(AVG_DAILY_SENTIMENT) OVER (
        PARTITION BY TICKER ORDER BY SENTIMENT_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ), 4) AS SENTIMENT_MA_3D,
    -- Momentum signal: short-term vs long-term sentiment
    CASE
        WHEN AVG(AVG_DAILY_SENTIMENT) OVER (
            PARTITION BY TICKER ORDER BY SENTIMENT_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
        ) > AVG(AVG_DAILY_SENTIMENT) OVER (
            PARTITION BY TICKER ORDER BY SENTIMENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
        ) + 0.1 THEN 'HYPE_RISING'
        WHEN AVG(AVG_DAILY_SENTIMENT) OVER (
            PARTITION BY TICKER ORDER BY SENTIMENT_DATE ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
        ) < AVG(AVG_DAILY_SENTIMENT) OVER (
            PARTITION BY TICKER ORDER BY SENTIMENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
        ) - 0.1 THEN 'HYPE_FALLING'
        ELSE 'STABLE'
    END AS MOMENTUM_SIGNAL
FROM daily_sentiment;

-- ============================================
-- Verify
-- ============================================
SHOW DYNAMIC TABLES IN DATABASE SNOWPULSE_DB;
